service: vaporwave-gifs

custom: 
  stage: dev #Configure your stage if you want
  region: us-west-2 #Configure your AWS region if you want
  profile: personal #Configure your AWS profile if you want

provider:
  name: aws
  runtime: python3.6
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  profile: ${self:custom.profile}
  memorySize: 256
  timeout: 300
  environment:
    giphy_api_key: 9z45C5QgbhbPo32cY55cyHuB8iVSHhV4
    giphy_tag: vaporwave
    gif_width: 800
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:*
      Resource: [
        "*"
      ]

functions:
  vaporwave-gifs:
    name: vaporwave-gifs
    handler: app.handler
